version: "3.4"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - tgblog-html:/usr/share/nginx/html
    ports:
      - "8080:80"

  tgblog:
    container_name: tgblog
    build: .
    volumes:
      - tgblog-html:/usr/share/nginx/html
      - tgblog-data:/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - AUTHOR=${AUTHOR}
      - TITLE=${TITLE}
      - SLEEP=${SLEEP}

volumes:
  tgblog-data:
  tgblog-html:
