version: "3.4"
services:
  web:
    image: nginx:alpine
    volumes:
      - tgblog-html:/usr/share/nginx/html
    ports:
      - "8080:80"

  tgblog:
    build: .
    volumes:
      - tgblog-html:/usr/share/nginx/html
      - tgblog-data:/data
    environment:
      - TELEGRAM_TOKEN=1444624203:AAF-X6pIq6Jm4TmI8KeTiaPWUiXdDEkIm_c
      - CHAT_ID=-1001382641583
      - AUTHOR=Dmitry Bikulov
      - TITLE=ksar.dev channel
      - SLEEP=10

volumes:
  tgblog-data:
  tgblog-html:
